gui:
  border: single
  showIcons: false
  theme:
    activeBorderColor:
      - '#d2dade'
      - bold
    inactiveBorderColor:
      - '#c0c8cc'
    optionsTextColor:
      - '#a7d3b7'
    selectedLineBgColor:
      - '#d2dade'
    selectedLineFgColor:
      - '#1d2021'
    cherryPickedCommitBgColor:
      - '#31132a'
    cherryPickedCommitFgColor:
      - '#e1b8d5'
    unstagedChangesColor:
      - '#c7cb9e'
    defaultFgColor:
      - '#c0c8cc'
    searchingActiveBorderColor:
      - '#e2c09e'

  authorColors:
    '*': '#ebb8b5'

  spinner:
    frames:
     - '⠋'
     - '⠙'
     - '⠹'
     - '⠸'
     - '⠼'
     - '⠴'
     - '⠦'
     - '⠧'
     - '⠇'
     - '⠏'
git:
  parseEmoji: true
