gui:
  border: single
  showIcons: false
  theme:
    activeBorderColor:
      - '#d2dade'
      - bold
    inactiveBorderColor:
      - '#c0c8cc'
    optionsTextColor:
      - '#9bd7b2'
    selectedLineBgColor:
      - '#d2dade'
    selectedLineFgColor:
      - '#1d2021'
    cherryPickedCommitBgColor:
      - '#350c2d'
    cherryPickedCommitFgColor:
      - '#e9b3da'
    unstagedChangesColor:
      - '#c8cc90'
    defaultFgColor:
      - '#c0c8cc'
    searchingActiveBorderColor:
      - '#eabd8f'

  authorColors:
    '*': '#f7b2af'

  spinner:
    frames:
     - '⠋'
     - '⠙'
     - '⠹'
     - '⠸'
     - '⠼'
     - '⠴'
     - '⠦'
     - '⠧'
     - '⠇'
     - '⠏'
git:
  parseEmoji: true
