gui:
  border: single
  showIcons: false
  theme:
    activeBorderColor:
      - '#d2dade'
      - bold
    inactiveBorderColor:
      - '#c0c8cc'
    optionsTextColor:
      - '#c7cd90'
    selectedLineBgColor:
      - '#d2dade'
    selectedLineFgColor:
      - '#11262d'
    cherryPickedCommitBgColor:
      - '#251945'
    cherryPickedCommitFgColor:
      - '#c8bdf7'
    unstagedChangesColor:
      - '#eabd8e'
    defaultFgColor:
      - '#c0c8cc'
    searchingActiveBorderColor:
      - '#f7b3af'

  authorColors:
    '*': '#eab3d9'

  spinner:
    frames:
     - '⠋'
     - '⠙'
     - '⠹'
     - '⠸'
     - '⠼'
     - '⠴'
     - '⠦'
     - '⠧'
     - '⠇'
     - '⠏'
git:
  parseEmoji: true
