# Colors (mini)

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#c0c8cc'

# Normal colors
[colors.normal]
black   = '#515556'
red     = '#ebb8b5'
green   = '#a7d3b7'
yellow  = '#c7cb9e'
blue    = '#c7c0eb'
magenta = '#e1b8d5'
cyan    = '#98d3d7'
white   = '#d2dade'

# Bright colors
[colors.bright]
black   = '#515556'
red     = '#ebb8b5'
green   = '#a7d3b7'
yellow  = '#c7cb9e'
blue    = '#c7c0eb'
magenta = '#e1b8d5'
cyan    = '#98d3d7'
white   = '#d2dade'
	