# Colors (mini)

# Default colors
[colors.primary]
background = '#11262d'
foreground = '#c0c8cc'

# Normal colors
[colors.normal]
black   = '#445a62'
red     = '#eab3d9'
green   = '#c7cd90'
yellow  = '#eabd8e'
blue    = '#9dccf9'
magenta = '#c8bdf7'
cyan    = '#9bd7b3'
white   = '#d2dade'

# Bright colors
[colors.bright]
black   = '#445a62'
red     = '#eab3d9'
green   = '#c7cd90'
yellow  = '#eabd8e'
blue    = '#9dccf9'
magenta = '#c8bdf7'
cyan    = '#9bd7b3'
white   = '#d2dade'
	