# Colors (mini)

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#c0c8cc'

# Normal colors
[colors.normal]
black   = '#515556'
red     = '#f7b2af'
green   = '#9bd7b2'
yellow  = '#c8cc90'
blue    = '#c7bef7'
magenta = '#e9b3da'
cyan    = '#85d7dd'
white   = '#d2dade'

# Bright colors
[colors.bright]
black   = '#515556'
red     = '#f7b2af'
green   = '#9bd7b2'
yellow  = '#c8cc90'
blue    = '#c7bef7'
magenta = '#e9b3da'
cyan    = '#85d7dd'
white   = '#d2dade'
	