# Colors (mini)

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#c0c8cc'

# Normal colors
[colors.normal]
black   = '#515556'
red     = '#e0bdbb'
green   = '#b2cfbc'
yellow  = '#c7caac'
blue    = '#c6c2df'
magenta = '#d8bdd0'
cyan    = '#a9cfd2'
white   = '#d2dade'

# Bright colors
[colors.bright]
black   = '#515556'
red     = '#e0bdbb'
green   = '#b2cfbc'
yellow  = '#c7caac'
blue    = '#c6c2df'
magenta = '#d8bdd0'
cyan    = '#a9cfd2'
white   = '#d2dade'
	